subject = {}
        "name": "",
        "level": "",
        "score": "",
        "calculated_gpa": 0.0

        if level == 1:
            if score == 100:
                retrurn 5.0
            elif score == 99
                return 4.9
            elif score == 98
                retrurn 4.8
            elif score == 97
                return 4.7
            elif score == 96
                return 4.6
            elif score == 95
                return 4.5
            elif score == 94
                return 4.4
            elif score == 93
                return 4.3
            elif score == 92
                return 4.2
            elif score == 91
                return 4.1
            elif score == 90
                return 4.0
            elif score == 89
                return 3.9
            elif score == 88
                return 3.8
            elif score == 87
                return 3.7
            elif score == 86
                return 3.6
            elif score == 85
                return 3.5
            elif score == 84
                return 3.4
            elif score == 83
                return 3.3
            elif score == 82
                return 3.2
            elif score == 81
                return 3.1
            elif score == 80
                return 3.0
            elif score == 79
                return 2.9
            elif score == 78
                return 2.8
            elif score == 77
                return 2.7
            elif score == 76
                return 2.6
            elif score == 75
                return 2.5
            elif score == 74
                return 2.4
            elif score == 73
                return 2.3
            elif score == 72
                return 2.2
            elif score == 71
                return 2.1
            elif score == 70
                return 2.0

        if level == 2:
            if score == 100:
                return 5.5
            elif score == 99
                return 5.4
            elif score == 98
                return 5.3
            elif score == 97
                return 5.2
            elif score == 96
                return 5.1
            elif score == 95
                return 5.0
            elif score == 94
                return 4.9
            elif score == 93
                return 4.8
            elif score == 92
                return 4.7
            elif score == 91
                return 4.6
            elif score == 90
                return 4.5
            elif score == 89
                return 4.4
            elif score == 88
                return 4.3
            elif score == 87
                return 4.2
            elif score == 86
                return 4.1
            elif score == 85
                return 4.0
            elif score == 84
                return 3.9
            elif score == 83
                return 3.8
            elif score == 82
                return 3.7
            elif score == 81
                return 3.6
            elif score == 80
                return 3.5
            elif score == 79
                return 3.4
            elif score == 78
                return 3.3
            elif score == 77
                return 3.2
            elif score == 76
                return 3.1
            elif score == 75
                return 3.0
            elif score == 74
                return 2.9
            elif score == 73
                return 2.8
            elif score == 72
                return 2.7
            elif score == 71
                return 2.6
            elif score == 70
                return 2.5
            elif score == 69
                return 2.4
            elif score == 68
                return 2.3
            elif score == 67
                return 2.2
            elif score == 66
                return 2.1
            elif score == 65
                return 2.0


subjects = []

while true:
    subject["name"] = input("enter name: "))
    subject["level"] = int(input("enter level: ")
    subject["grade"] = int(input("enter grade: "))
    subject["gpa"] = float(input("enter gpa: "))
    subjects.append(subject)
    answer = input("are you done? [y/n]:")
    if answer.lower == 'y':
        break
return subjects
    if answer == 'n':
    
def calculate_weighted_gpa(subject):
    pass

def calculate_overall_average():
    pass

def display_score():
    pass

def main():

    subjects = get_subjects()
    level = subject["level"]
    score = subject["score"]


print(subject)
for k,v in subject.items():


def man():
    print("GPA calculator")


main()